spring.application.name=DietiEstates25
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PW}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

geoapify.api.key=${GEOAPIFY_API_KEY}

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${MAILTRAP_USER}
spring.mail.password=${MAILTRAP_PW}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=100MB

cloud.aws.credentials.access-key={$AWS_ACCESS_KEY}
cloud.aws.credentials.secret-key={$AWS_SECRET_KEY}
cloud.aws.region.static={AWS_REGION}
aws.s3.bucket.name=dietiestates25-photo